root = "."
tmp_dir = "tmp"

[build]
  pre_cmd = ["templ generate"]
  cmd = "go build -o ./tmp/server ./cmd/server"
  bin = "./tmp/server"
  include_ext = ["go", "templ"]
  exclude_dir = ["tmp", "static", "db/generated"]
  delay = 1000
